config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/auth/facebook/callback' => 'sessions#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/account', to: 'users#show'

  get '/cart', to: 'carts#show'

  post '/add_to_cart', to: 'recipes#add_to_cart'
  delete '/remove_from_cart', to: 'recipes#remove_from_cart'

  resources :recipes, only: [:show, :new, :index, :create, :edit, :update] do
    resources :ingredients
  end

  resources :ingredients, only: [:new, :edit, :create] do
    resources :recipes
  end

  resources :users

  resources :carts

  resources :cart_recipes



end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#   id                  :integer            not null, primary key
#   name                :string     
#   instructions        :string
#   image               :string
#   created_at          :datetime           not null
#   updated_at          :datetime           not null
#

class Recipe < ApplicationRecord
    has_many :recipe_ingredients
    has_many :cart_recipes
    has_many :ingredients, through: :recipe_ingredients
    has_many :carts, through: :cart_recipes

    validates :name, presence: true

    accepts_nested_attributes_for :ingredients

    MEASUREMENTS = [
        /cups?/,
        /teaspoons?/,
        /tablespoons?/,
        /pints?/,
        /quarts?/,
        /gallons?/,
        /pounds?/,
        /ounces?/
    ]

    # scope :filter_by_ingredient, -> (ingredient) {includes()}


    def ingredients_attributes=(ingredient_attributes)
        ingredient_attributes.values.each do |ingredient_attribute|
            ingredient = Ingredient.find_or_create_by(ingredient_attribute)
            self.ingredients << ingredient
        end
    end

    def recipe_ingredients_attributes=(recipe_ingredient_attributes)
        recipe_ingredient_attributes.values.each do |recipe_ingredient_attribute|
            if recipe_ingredient_attribute[:ingredient_attributes][:name].present?
                
                ingredient = Ingredient.find_or_create_by(:name => recipe_ingredient_attribute[:ingredient_attributes][:name])

                recipe_ingredient = RecipeIngredient.find_or_create_by(:ingredient_id => ingredient.id)
                recipe_ingredient.update(:quantity => recipe_ingredient_attribute[:quantity])

                self.recipe_ingredients << recipe_ingredient
            elsif recipe_ingredient_attribute[:ingredient_id].present?
                ingredient = Ingredient.find_by(:id => recipe_ingredient_attribute[:ingredient_id])

                recipe_ingredient = RecipeIngredient.find_or_create_by(:ingredient_id => ingredient.id)
                recipe_ingredient.update(:quantity => recipe_ingredient_attribute[:quantity])

                self.recipe_ingredients << recipe_ingredient
            end
        end
    end

    def self.find_or_create_from_api(arrayOfRecipes)
        arrayOfRecipes.each do |recipe_data|
            recipe = Recipe.find_or_create_by(:name => recipe_data['recipe']['label'])
            recipe.update(:image => recipe_data['recipe']['image'])
            recipe_data['recipe']['ingredients'].each do |ingredient_data|
                ingredient_text_parsed = ingredient_data['text'].split(" ")
                MEASUREMENTS.each do |measurement|
                    if ingredient_data['text'].include?(measurement.to_s)
                        ingredient_text_parsed = ingredient_data['text'].partition(measurement.to_s)
                        break
                    end
                end
                ingredient = Ingredient.find_or_create_by(:name => ingredient_text_parsed[-1])
                recipe_ingredient = RecipeIngredient.find_or_create_by(:recipe_id => recipe.id, :ingredient_id => ingredient.id)
                recipe_ingredient.update(:quantity => ingredient_text_parsed[0...-1].join)
                recipe.recipe_ingredients << recipe_ingredient
            end
        end
    end

    # model scope methods
    def self.filter_by_ingredient(ingredient_name)
        self.all.includes(:ingredients).where(ingredients: { name: ingredient_name.downcase })
    end

    def self.containsmilk
        self.all.includes(:ingredients).where(ingredients: { name: 'Milk' } )
    end
end

app/controllers/recipes_controller.rb
# == Schema Information
#
# Table name: recipes
#
#   id                  :integer            not null, primary key
#   name                :string     
#   instructions        :string
#   image               :string
#   created_at          :datetime           not null
#   updated_at          :datetime           not null
#

class RecipesController < ApplicationController
    before_action :require_login
    before_action :set_recipe, only: [:show, :edit, :update, :add_to_cart, :remove_from_cart]
    
    def index
        if params[:ingredient].present?
            # use heroku vars
            edamam = EdamamService.new
            body = edamam.recipes(params[:ingredient])
            Recipe.find_or_create_from_api(body)
            @recipes = Recipe.filter_by_ingredient(params[:ingredient])
        end

        recipes = Recipe.all
        
        respond_to do |format|
            format.html { render :index }
            format.json { render json: recipes }
        end
    end

    def show
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @recipe }
        end
    end

    def new
        @recipe = Recipe.new
        5.times {@recipe.recipe_ingredients.build}

    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            render json: @recipe, status: 201
        else
            render :new
        end
    end

    def edit

    end

    def update
        if @recipe.update(recipe_params)
            redirect_to recipe_path(@recipe)
        else
            render :edit
        end
    end

    def destroy

    end

    def add_to_cart
        CartRecipe.find_or_create_by(cart_id: session[:cart_id], recipe_id: params[:id])

        flash[:notice] = "Recipe successfully added"

        redirect_to recipe_path(@recipe)
    end

    def remove_from_cart
        cart = Cart.find_by(:id => session[:cart_id])
        cart_recipe = CartRecipe.find_by(cart_id: cart.id, recipe_id: @recipe.id)

        cart_recipe.destroy

        flash[:notice] = "Recipe successfully removed"
        redirect_to cart_path
    end



    private

    def set_recipe
        @recipe = Recipe.find_by(:id => params[:id])
    end

    def recipe_params
        params.require(:recipe).permit(:name, :content, ingredient_ids: [], recipe_ingredients_attributes: [:quantity, :ingredient_id, ingredient_attributes: [:name]])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for recipe do |f| %>
    <%= f.label "Name" %>
    <%= f.text_field :name %>
    <%= f.label "Instructions" %>
    <%= f.text_area :instructions %>
    <%#<%= f.collection_select :ingredient_ids, Ingredient.all, :id, :name %>
    <%= f.fields_for :recipe_ingredients do |recipe_ingredients_fields| %>
        <p>
        <%= recipe_ingredients_fields.collection_select :ingredient_id, Ingredient.all, :id, :name, prompt: true %>
        <%= recipe_ingredients_fields.label "Quantity" %>
        <%= recipe_ingredients_fields.text_field :quantity %>
        <%= recipe_ingredients_fields.fields_for :ingredient, recipe_ingredients_fields.object.build_ingredient do |ingredient_fields| %>
            <%= ingredient_fields.label "New Ingredient Name" %>
            <%= ingredient_fields.text_field :name %> 
        <% end %>
        </p>
    <% end %>

    <%= f.submit %>
<% end %>

<div class="new-recipe">


</div>

<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
      //prevent form from submitting the default way
      event.preventDefault();
 
      var values = $(this).serialize();
 
      var posting = $.post('/recipes', values);
 
      posting.done(function(data) {
        let recipe = data;
        let ingredients = recipe.ingredients.map(ingredient => {
            return(
                `<li>${ingredient.name}</li>`
            )
        })

        $(".new-recipe").html(`<h2>${recipe.name}</h2><p>Ingredients:</p><ul>${ingredients}</ul>`);
      });
    });
  });
</script>

app/views/recipes/edit.html.erb
<%= render partial: 'form', locals: { recipe: @recipe } %>

app/views/recipes/index.html.erb
<div class="recipe-filter">
    <%= form_tag("/recipes", method: "get") do %>
        <%= text_field_tag "ingredient", nil, placeholder: "Ingredient" %>
        <%= button_tag do %>
            <i class="fas fa-search"></i>
        <% end %>
    <% end %>
</div>

<div class="recipes">
    <% if @recipes %>
        <% @recipes.each do |recipe|%>
            <div class="recipe-card">
                <img src="<%= recipe.image %>" />
                <%= link_to recipe.name, recipe_path(recipe) %>
            </div>
        <% end %>
    <% end %>
</div>

<%= link_to "New Recipe", new_recipe_path %><br>

app/views/recipes/new.html.erb
<%= render partial: 'form', locals: { recipe: @recipe } %>

app/views/recipes/show.html.erb
<h1><%= link_to @recipe.name, recipe_path(@recipe) %></h1>

<h3>Ingredients:</h3>
<ul>
    <% @recipe.ingredients.each do |ingredient| %>
        <li><%= @recipe.recipe_ingredients.find{ |i| i.ingredient_id == ingredient.id }.quantity  %> <%= link_to ingredient.name, recipe_ingredient_path(@recipe, ingredient) %></li>
    <% end %>
</ul>

<%= link_to "New Ingredient", new_recipe_ingredient_path(@recipe) %>

<%= link_to "Edit Recipe", edit_recipe_path(@recipe) %>

<%= link_to "Add to Cart", {controller: "recipes", action: "add_to_cart", id: @recipe}, method: "post" %>